version: '3.9'

volumes:
  wordpress:
    name: wordpress_volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kzegani/data/wordpress

  DB:
    name: mariadb_volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kzegani/data/DB

networks:
  inception:
    name: inception
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      inception:
        ipv4_address: 192.168.1.3
    env_file:
      - .env
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - DB:/var/lib/mysql/
    networks:
      inception:
        ipv4_address: 192.168.1.4
    env_file:
      - .env
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - nginx
    networks:
      inception:
        ipv4_address: 192.168.1.5
    env_file:
      - .env
    restart: on-failure

  html:
    build: ./requirements/bonus/html
    image: html
    container_name: html
    networks:
      inception:
        ipv4_address: 192.168.1.2
    env_file:
      - .env
    restart: on-failure

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    networks:
      inception:
        ipv4_address: 192.168.1.6
    restart: on-failure

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    ports:
      - "8081:80"
    networks:
      inception:
        ipv4_address: 192.168.1.7
    volumes:
      - DB:/var/lib/mysql/
    restart: on-failure

  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    container_name: cadvisor
    ports:
      - "8082:8080"
    networks:
      inception:
        ipv4_address: 192.168.1.8
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: on-failure

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    ports:
      - "20:20"
    networks:
      inception:
        ipv4_address: 192.168.1.9
    volumes:
      - wordpress:/home/kzegani
    restart: on-failure
